# Generated by Django 5.2.13 on 2026-04-26 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0002_valoracion"),
    ]

    operations = [
        migrations.AddField(
            model_name="receta",
            name="guardadas",
            field=models.ManyToManyField(
                blank=True,
                related_name="recetas_guardadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
